// Generated by gencpp from file motion_model/motion_model_msgs.msg
// DO NOT EDIT!


#ifndef MOTION_MODEL_MESSAGE_MOTION_MODEL_MSGS_H
#define MOTION_MODEL_MESSAGE_MOTION_MODEL_MSGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_model
{
template <class ContainerAllocator>
struct motion_model_msgs_
{
  typedef motion_model_msgs_<ContainerAllocator> Type;

  motion_model_msgs_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  motion_model_msgs_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::motion_model::motion_model_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_model::motion_model_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct motion_model_msgs_

typedef ::motion_model::motion_model_msgs_<std::allocator<void> > motion_model_msgs;

typedef boost::shared_ptr< ::motion_model::motion_model_msgs > motion_model_msgsPtr;
typedef boost::shared_ptr< ::motion_model::motion_model_msgs const> motion_model_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_model::motion_model_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_model::motion_model_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_model::motion_model_msgs_<ContainerAllocator1> & lhs, const ::motion_model::motion_model_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_model::motion_model_msgs_<ContainerAllocator1> & lhs, const ::motion_model::motion_model_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_model

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_model::motion_model_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_model::motion_model_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_model::motion_model_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_model::motion_model_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_model::motion_model_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_model::motion_model_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_model::motion_model_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::motion_model::motion_model_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71344c0ba019367ULL;
  static const uint64_t static_value2 = 0x56dc45bcd89ef437ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_model::motion_model_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_model/motion_model_msgs";
  }

  static const char* value(const ::motion_model::motion_model_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_model::motion_model_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::motion_model::motion_model_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_model::motion_model_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_model_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_model::motion_model_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_model::motion_model_msgs_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_MODEL_MESSAGE_MOTION_MODEL_MSGS_H
